spring.application.name=BoosterHub

spring.datasource.url=jdbc:postgresql://localhost:5432/boosterhub
spring.datasource.username=boosterhub
spring.datasource.password=boosterhub

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration